server:
  port: 8080

spring:
  cache:
    type: simple
  redis.host: redis
  data:
    redis:
      repositories.enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

kafka:
  bootstrap-servers: kafka-service.skillbox-alpha-kafka.svc.cluster.local:9092
  consumer:
    group-id: streaming.1
    concurrency: 3
    max.poll.interval.ms: 1000
    spring.json.trusted.packages: ru.skillbox.diplom.group35.*
  producer:
    retries: 3

app:
  topic:
    account: topic-account

logging:
  level:
    org.springframework: info
  file:
    name: application.log
  logback:
    rolling policy:
      max-history: 3
      clean-history-on-start: true