server:
  port: 8080

spring:
  cache:
    type: simple
  redis.host: redis
  data:
    redis:
      repositories.enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

kafka:
  bootstrap-servers: 82.202.214.42:9094
  consumer:
    group-id: streaming.1
    concurrency: 3
    max-poll-interval-ms: 1000
    spring-json-trusted-packages: ru.skillbox.diplom.group35.*
  producer:
    retries: 3
  topic:
    partition-count: 3
    replication-factor: 1
    reply-account: t.account.online
    reply-dialog: t.dialog.message.in
    request-dialog: t.dialog.message.out
    request-notification: event.streaming

logging:
  level:
    org.springframework: info
  file:
    name: application.log
  logback:
    rolling policy:
      max-history: 3
      clean-history-on-start: true