server:
  port: 8080

kafka:
#  bootstrap-servers: 82.202.214.42:9094
  bootstrap-servers: localhost:9092
  consumer:
    group-id: streaming.1
    concurrency: 1
    max-poll-interval-ms: 1000
    spring-json-trusted-packages: ru.skillbox.diplom.group35.*
  producer:
    retries: 3
  topic:
    partition-count: 1
    dialog-partition-count: 1
    replication-factor: 1
    reply-account: t.account.online
    reply-dialog: t.dialog.message.in
    request-dialog: t.dialog.message.out
    request-notification: event.streaming

spring:
  security:
    user:
      name: streaming
      password: streaming
  boot:
    admin:
      client:
        enabled: false
  cloud:
    kubernetes:
      config:
        enabled: false
      reload:
        monitoring-config-maps: false
      enabled: false

  cache:
    type: simple
  redis.host: redis
  data:
    redis:
      repositories.enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

logging:
  level:
    org.springframework: info
  file:
    name: application.log
  logback:
    rolling policy:
      max-history: 3
      clean-history-on-start: true