server:
  port: 8080

app:
  topic:
    account: topic-account

spring:
  security:
    user:
      name: streaming
      password: streaming
  boot:
    admin:
      client:
        enabled: false
  cloud:
    kubernetes:
      config:
        enabled: false
      reload:
        monitoring-config-maps: false
      enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: post
    open-in-view: false

  cache:
    type: simple
  redis.host: redis
  data:
    redis:
      repositories.enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

logging:
  level:
    org.springframework: debug
  file:
    name: application.log
  logback:
    rolling policy:
      max-history: 3
      clean-history-on-start: true